//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppMVCforCUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentData
    {
        public int Id { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Sir_Name { get; set; }
        public string Email { get; set; }
        public string Guadian_Name { get; set; }
        public int Phone_Number { get; set; }
        public string County { get; set; }
        public string Sub_counry { get; set; }
        public string Location { get; set; }
        public string Village { get; set; }
    }
}
